Guess the architecture, and minor fixes

diff --git a/bin/yc b/bin/yc
--- a/bin/yc
+++ b/bin/yc
@@ -1,6 +1,19 @@
 #!/bin/sh
 
-ARCH=linux32
+ARCH=unknown
+
+case `uname -a` in
+Linux*x86_64*) ARCH=linux64;;
+Linux*) ARCH=linux32;;
+Darwin*) ARCH=osx;;
+CYG*) ARCH=win32;;
+MINGW*) ARCH=win32;;
+esac
+
+if [ "$ARCH" == "unknown" ]; then
+    echo "Failed to guess architecture for native libraries, sorry!" 1>&2
+    exit 2
+fi
 
 YLDIR=`dirname $0`/..
 
